{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
spec:
  {{- with .Values.certificate.commonName }}
  commonName: {{ . }}
  {{- end }}
  dnsNames:
  {{- range $domain := .Values.certificate.domains }}
  - {{ $domain | quote }}
  {{- end }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: {{ .Values.certificate.issuer }}
  secretName: {{ .Values.certificate.secretName }}
  usages:
  - digital signature
  - key encipherment
{{- end }}