{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: oh-psql-scripts-configmap
data:
  init.sql: |
    CREATE DATABASE litellm;
    GRANT ALL PRIVILEGES ON DATABASE litellm TO postgres;
    CREATE DATABASE keycloak;
    GRANT ALL PRIVILEGES ON DATABASE keycloak TO postgres;
    CREATE DATABASE openhands;
    GRANT ALL PRIVILEGES ON DATABASE openhands TO postgres;
    CREATE DATABASE postgres_langfuse;
    GRANT ALL PRIVILEGES ON DATABASE postgres_langfuse TO postgres;
    CREATE DATABASE bitnami_keycloak;
    GRANT ALL PRIVILEGES ON DATABASE bitnami_keycloak TO postgres;
    CREATE DATABASE runtime_api_db;
    GRANT ALL PRIVILEGES ON DATABASE runtime_api_db TO postgres;
{{- end }}
