apiVersion: v1
kind: Service
metadata:
  name: openhands-integrations-service
  labels:
    {{- include "openhands.componentLabels" (dict "context" . "component" "integrations") | nindent 4 }}
    app: openhands-integrations
spec:
  ports:
  - name: openhands-integrations
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    {{- include "openhands.componentSelectorLabels" (dict "context" . "component" "integrations") | nindent 4 }}
  type: ClusterIP