apiVersion: v1
kind: Service
metadata:
  name: openhands-integrations-service
  labels:
    app: openhands-integrations
spec:
  ports:
  - name: openhands-integrations
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: openhands-integrations
  type: ClusterIP