{{- $hostname := .Values.laminar.frontend.ingress.hostname }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: laminar-frontend-gcp-ingress
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ $hostname }}
    {{- with .Values.laminar.frontend.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.laminar.frontend.ingress.className | default "gce" }}
  rules:
    - host: {{ $hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: laminar-frontend-service
                port:
                  number: {{ .Values.laminar.frontend.service.port | default 80 }}
