{{- if and .Values.ingress.enabled .Values.automation.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-automation-prefix
spec:
  stripPrefix:
    prefixes:
      - /automation
{{- end }}
