{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: openhands-monitoring
spec:
  selector:
    matchLabels:
      app: openhands
  endpoints:
  - port: 3000
    interval: 30s
    # We currently need the trailing slash
    path: /internal/metrics/
{{- end }}
