{{- if .Values.proactiveConvoClean.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-proactive-convo-clean
  labels:
    app: {{ .Release.Name }}-proactive-convo-clean
spec:
  schedule: {{ .Values.proactiveConvoClean.schedule | quote }}
  concurrencyPolicy: {{ .Values.proactiveConvoClean.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .Values.proactiveConvoClean.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.proactiveConvoClean.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.proactiveConvoClean.backoffLimit }}
      template:
        metadata:
          labels:
            app: {{ .Release.Name }}-proactive-convo-clean
        spec:
          serviceAccountName: {{ .Values.serviceAccount.name }}
          restartPolicy: OnFailure
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ .Release.Name }}-proactive-convo-clean
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
              command: ["python", "-m", "sync.clean_proactive_convo_table"]
              resources:
                {{- toYaml .Values.proactiveConvoClean.resources | nindent 16 }}
              env:
                {{- include "openhands.env" . | nindent 16 }}
{{- end }}
