{{- define "runtime-api.env" }}
{{- range $key, $value := .Values.env }}
- name: {{ $key }}
  value: {{ $value | quote }}
{{- end }}
- name: RUNTIME_DEAD_SECONDS
  value: {{ printf "%.0f" .Values.cleanup.dead_seconds | quote }}
{{- if .Values.ingressBase.enabled }}
- name: INGRESS_BASE
  value: "/ingress-base/base-ingress.yaml"
{{- end }}
{{- if .Values.datadog.enabled }}
# Datadog environment variables
- name: DD_AGENT_HOST
  value: "datadog-agent.all-hands-system.svc.cluster.local"
- name: DD_TRACE_AGENT_PORT
  value: "8126"
- name: DD_DOGSTATSD_PORT
  value: "8125"
- name: DD_SERVICE
  value: "runtime-api"
- name: DD_ENV
  value: {{ .Values.datadog.env | default "dev" | quote }}
- name: DD_LOGS_INJECTION
  value: "true"
- name: DD_TRACE_ENABLED
  value: "true"
- name: DD_TRACE_SAMPLING_RULES
  value: '[{"resource": "GET /health", "sample_rate": 0.0}, {"resource": "GET /internal/metrics", "sample_rate": 0.0}]'
{{- end }}
{{- if .Values.postgresql.enabled }}
- name: DB_HOST
  value: "{{ .Release.Name }}-postgresql"
- name: DB_USER
  value: "{{ .Values.postgresql.auth.username }}"
- name: DB_NAME
  value: "{{ .Values.postgresql.auth.database }}"
{{- else if .Values.database.create }} # should only be true for AWS deploys
- name: DB_HOST
  value: "{{.Values.database.host}}"
- name: DB_PORT
  value: "{{.Values.database.port}}"
- name: DB_USER
  value: "{{.Values.database.new_user}}"
- name: DB_NAME
  value: "{{.Values.database.name}}"
{{- end }}
- name: DB_PASS
  valueFrom:
    secretKeyRef:
      name: {{ .Values.postgresql.auth.existingSecret }}
      key: password
{{- end }}
