{{- define "runtime-api.dbInitContainers" }}
- name: wait-for-db
  image: "bitnamilegacy/postgresql:latest"
  command: ['sh', '-c']
  args:
    - |
      echo "Waiting for PostgreSQL at $DB_HOST to be ready..."
      until PGPASSWORD=$DB_PASS pg_isready -h $DB_HOST -p 5432 -U $DB_USER > /dev/null 2>&1; do
        echo "PostgreSQL is unavailable - sleeping for 2 seconds"
        sleep 2
      done
      echo "PostgreSQL is up and running!"
  env:
    {{- include "runtime-api.env" . | nindent 4 }}
{{- if .Values.databaseMigrations.createDatabases }}
- name: create-db
  image: "bitnamilegacy/postgresql:latest"
  command: ['sh', '-c']
  args:
    - |
      export PGPASSWORD=$DB_ADMIN_PASSWORD

      echo "Checking if the DB \"$DB_NAME\" and user \"$DB_USER\" exist..."
      # Create the database if it doesn't exist
      psql -h $DB_HOST -p 5432 -U $DB_ADMIN_USER -d postgres -tc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" | grep -q 1 || \
      psql -h $DB_HOST -p 5432 -U $DB_ADMIN_USER -d postgres -c "CREATE DATABASE $DB_NAME;"
      # Create the user if it doesn't exist
      psql -h $DB_HOST -p 5432 -U $DB_ADMIN_USER -d $DB_NAME -tc "SELECT 1 FROM pg_roles WHERE rolname='$DB_USER'" | grep -q 1 || \
      (psql -h $DB_HOST -p 5432 -U $DB_ADMIN_USER -d $DB_NAME -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASS'; GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;")
  env:
    - name: DB_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ .Values.externalDatabase.existingSecret }}
          key: admin_password
    {{- include "runtime-api.env" . | nindent 4 }}
{{- end }}
{{- if .Values.databaseMigrations.migrate }}
- name: migrate-db
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  command: ["alembic", "upgrade", "head"]
  env:
    {{- include "runtime-api.env" . | nindent 4 }}
  {{- if .Values.ingressBase.enabled }}
  volumeMounts:
    - name: ingress-base-config
      mountPath: /ingress-base
  {{- end }}
  resources:
    {{- toYaml .Values.jobSettings.resources | nindent 4 }}
{{- end }}
{{- end }}
