apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "runtime-api.fullname" . }}
  labels:
    {{- include "runtime-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "runtime-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "runtime-api.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.warmRuntimes.enabled }}
        - name: warm-runtimes-config
          configMap:
            name: {{ .Values.warmRuntimes.configMapName }}
      {{- end }}
      {{- if .Values.ingressBase.enabled }}
        - name: ingress-base-config
          configMap:
            name: {{ include "runtime-api.fullname" . }}-ingress-base
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            {{- include "runtime-api.env" . | nindent 12 }}
            - name: DB_POOL_SIZE
              value: {{ .Values.database.poolSize.api | default 5 | quote }}
            - name: DB_MAX_OVERFLOW
              value: {{ .Values.database.maxOverflow.api | default 10 | quote }}
            {{- if .Values.defaultAPIKeySecretName }}
            - name: DEFAULT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.defaultAPIKeySecretName }}
                  key: default-api-key
            {{- end }}
            
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-password
                  key: admin-password
            

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or .Values.warmRuntimes.enabled .Values.ingressBase.enabled }}
          volumeMounts:
          {{- if .Values.warmRuntimes.enabled }}
            - name: warm-runtimes-config
              mountPath: /config
          {{- end }}
          {{- if .Values.ingressBase.enabled }}
            - name: ingress-base-config
              mountPath: /ingress-base
          {{- end }}
          {{- end }}
