{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "runtime-api.fullname" . }}-ingress
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    {{- if .Values.ingress.prefixWithBranch }}
    - {{ .Values.branchSanitized }}.{{ .Values.ingress.host }}
    {{- else }}
    - {{ .Values.ingress.host }}
    {{- end }}
    secretName: {{ .Values.ingress.tlsSecretName | default (printf "%s-tls" (include "runtime-api.fullname" .)) }}
  {{- end }}
  rules:
    {{- if .Values.ingress.prefixWithBranch }}
    - host: {{ .Values.branchSanitized }}.{{ .Values.ingress.host }}
    {{- else }}
    - host: {{ .Values.ingress.host }}
    {{- end }}
      http:
        paths:
          - path: {{ .Values.ingress.path | default "/" }}
            pathType: {{ .Values.ingress.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "runtime-api.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
