{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: {{ include "runtime-api.fullname" . }}-monitoring
spec:
  selector:
    matchLabels:
      {{- include "runtime-api.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: 5000
    interval: 30s
    path: /metrics
{{- end }}
