image:
  repository: ghcr.io/all-hands-ai/runtime
  tag: 0.9.6-nikolaik
  pullPolicy: Always

runtimeClass: sysbox-runc

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi

# Security context settings for all pods
securityContext:
  runAsUser: 1000
  runAsNonRoot: true

nodeSelector:
  sysbox-install: "yes"

tolerations:
- key: "sysbox-runtime"
  operator: "Equal"
  value: "not-running"
  effect: "NoSchedule"
affinity: {}

nodeOverprovisioner:
  replicas: 10
  priorityClassName: node-overprovisioner-priority
  resources:
    requests:
      cpu: 2500m
      memory: 7500Mi
    limits:
      cpu: 2500m
      memory: 7500Mi
