{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: automation
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  {{- if .Values.tls.enabled }}
  tls:
  - hosts:
    {{- if .Values.ingress.prefixWithBranch }}
    - automation-{{ .Values.branchSanitized }}.{{ .Values.ingress.host }}
    {{- else }}
    - {{ .Values.ingress.host }}
    {{- end }}
    secretName: automation-{{ .Values.tls.env }}-tls
  {{- end }}
  rules:
  {{- if .Values.ingress.prefixWithBranch }}
  - host: automation-{{ .Values.branchSanitized }}.{{ .Values.ingress.host }}
  {{- else }}
  - host: {{ .Values.ingress.host }}
  {{- end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: automation
            port:
              number: 80
{{- end }}
