apiVersion: v1
kind: Service
metadata:
  name: automation
  labels:
    {{- include "automation.labels" . | nindent 4 }}
    app: automation
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    {{- include "automation.selectorLabels" . | nindent 4 }}
