apiVersion: v2
description: OpenHands is an AI-driven autonomous software engineer
name: openhands
appVersion: 0.53.3
version: 0.1.13
maintainers:
  - name: rbren
  - name: xingyao
  - name: tofarr
dependencies:
  - name: clickhouse
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 9.2.5
    condition: clickhouse.enabled
  - name: keycloak
    version: 24.5.2
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: keycloak.enabled
  - name: langfuse
    repository: https://langfuse.github.io/langfuse-k8s
    version: 1.2.13
    condition: langfuse.enabled
  - name: litellm-helm
    repository: oci://ghcr.io/berriai
    version: 0.1.664
    condition: litellm-helm.enabled
  - name: minio
    version: 5.0.10
    condition: filestore.ephemeral
    repository: https://charts.min.io/
  - name: postgresql
    version: 15.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 20.3.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
  - name: runtime-api
    repository: oci://ghcr.io/all-hands-ai/helm-charts
    version: 0.1.9
    condition: runtime-api.enabled
