apiVersion: v1
kind: Secret
metadata:
  name: automation-service-key
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  automation-service-key: {{ .Values.config.automation_service_key | b64enc | quote }}
