apiVersion: v1
kind: Secret
metadata:
  name: automation-webhook-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  webhook-secret: {{ .Values.config.automation_webhook_secret | b64enc | quote }}
