apiVersion: v1
kind: Secret
metadata:
  name: keycloak-realm
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  realm-name: {{ .Values.config.keycloak_realm_name | b64enc | quote }}
  provider-name: {{ .Values.config.keycloak_provider_name | b64enc | quote }}
  server-url: {{ "http://keycloak" | b64enc | quote }}
  client-id: {{ .Values.config.keycloak_client_id | b64enc | quote }}
  client-secret: {{ .Values.config.keycloak_client_secret | b64enc | quote }}
  smtp-password: {{ .Values.config.keycloak_smtp_password | b64enc | quote }}