{{- if .Values.config.laminar_project_api_key }}
apiVersion: v1
kind: Secret
metadata:
  name: lmnr-project-api-key
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  LMNR_PROJECT_API_KEY: {{ .Values.config.laminar_project_api_key | b64enc | quote }}
{{- end }}
