apiVersion: v1
kind: Secret
metadata:
  name: openhands-env-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- if .Values.config.anthropic_api_key }}
  LLM_API_KEY: '{{ .Values.config.anthropic_api_key }}'
  LLM_MODEL: 'anthropic/claude-sonnet-4-5-20250929'
  LLM_BASE_URL: 'https://api.anthropic.com'
  {{- end }}
  {{- if .Values.config.openai_api_key }}
  LLM_API_KEY: {{ .Values.config.openai_api_key }}
  {{- end }}
  {{- if .Values.config.google_gemini_api_key }}
  LLM_API_KEY: {{ .Values.config.google_gemini_api_key }}
  {{- end }}
  {{- if .Values.config.google_vertex_credentials }}
  GOOGLE_APPLICATION_CREDENTIALS_JSON: {{ .Values.config.google_vertex_credentials }}
  {{- end }}
  {{- if .Values.config.deepseek_api_key }}
  LLM_API_KEY: {{ .Values.config.deepseek_api_key }}
  {{- end }}
  {{- if .Values.config.mistral_api_key }}
  LLM_API_KEY: {{ .Values.config.mistral_api_key }}
  {{- end }}
  {{- if .Values.config.azure_api_key }}
  LLM_API_KEY: {{ .Values.config.azure_api_key }}
  {{- end }}
  {{- if .Values.config.groq_api_key }}
  LLM_API_KEY: {{ .Values.config.groq_api_key }}
  {{- end }}
  {{- if .Values.config.openrouter_api_key }}
  LLM_API_KEY: {{ .Values.config.openrouter_api_key }}
  {{- end }}
  {{- if .Values.config.custom_api_key }}
  LLM_API_KEY: {{ .Values.config.custom_api_key }}
  {{- end }}
