{{- if .Values.config.plugin_directory_identity_shared_secret }}
apiVersion: v1
kind: Secret
metadata:
  name: plugin-directory-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  identity-shared-secret: {{ .Values.config.plugin_directory_identity_shared_secret | b64enc | quote }}
  session-secret: {{ .Values.config.plugin_directory_session_secret | b64enc | quote }}
  oidc-client-secret: {{ .Values.config.plugin_directory_oidc_client_secret | b64enc | quote }}
{{- end }}
