apiVersion: v1
kind: Secret
metadata:
  name: postgres-password
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.config.postgres_username | b64enc | quote }}
  password: {{ .Values.config.postgres_password | b64enc | quote }}
  postgres-password: {{ .Values.config.postgres_password | b64enc | quote }}