apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: openhands
spec:
  title: OpenHands
  icon: https://raw.githubusercontent.com/All-Hands-AI/OpenHands/main/frontend/public/apple-touch-icon.png
  releaseNotes: |
    ## OpenHands v0.47.0

    OpenHands is an AI-driven autonomous software engineer that can help you build, debug, and deploy applications.

  additionalNamespaces:
    - openhands

  statusInformers:
    # openhands
    - openhands/deployment/openhands
    - openhands/service/openhands-service
    - openhands/ingress/openhands-root-ingress
    - openhands/deployment/openhands-integrations
    - openhands/service/openhands-integrations-service
    - openhands/ingress/openhands-integrations-ingress
    - openhands/deployment/openhands-mcp
    - openhands/service/openhands-mcp-service
    - openhands/ingress/openhands-mcp-ingress

    # keycloak
    - openhands/statefulset/keycloak
    - openhands/service/keycloak

    # postgres (CNPG)
    - '{{repl if ConfigOptionEquals "postgres_type" "embedded_postgres"}}openhands/pod/oh-main-postgresql-1{{repl end}}'

    # valkey
    - openhands/deployment/openhands-valkey
    - openhands/service/openhands-valkey

    # lite-llm
    - openhands/deployment/openhands-litellm
    - openhands/service/openhands-litellm

    # minio
    - openhands/deployment/openhands-minio
    - openhands/service/openhands-minio

    # runtime-api chart
    - openhands/deployment/openhands-runtime-api
    - openhands/service/openhands-runtime-api
    - openhands/ingress/openhands-runtime-api-ingress
  ports:
    - serviceName: openhands
      servicePort: 3000
      localPort: 3000
      applicationUrl: "http://openhands"
