apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: image-loader
spec:
  chart:
    name: image-loader
    chartVersion: 0.1.2
    releaseName: image-loader
  helmVersion: v3
  useHelmInstall: true
  exclude: true
  weight: 30
  upgradeFlags: ["--wait"]
