#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///
"""Update OpenHands chart script."""


def main() -> None:
    pass


if __name__ == "__main__":
    main()
