apiVersion: v2
name: service-template
description: Template for FastAPI microservices with PostgreSQL backend
type: application
version: 0.1.1
appVersion: "0.1.0"
dependencies:
  - name: postgresql
    version: 15.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
