apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.nodeOverprovisioner.priorityClassName }}
value: -10
globalDefault: false
description: "This priority class is used for the node-overprovisioner deployment to ensure it gets evicted for other workloads."
