name: Helm Charts CI/CD

on:
  # Run on all pushes to main
  push:
    branches:
      - main
  # Run on PRs that modify charts or workflow
  pull_request:
    paths:
      - 'charts/**'
      - '.github/workflows/publish-helm-charts.yml'
  # Manual trigger
  workflow_dispatch:

jobs:
  test-charts:
    runs-on: ubuntu-latest
    # Skip duplicate runs for PRs (only run on PR, not on the push to the PR branch)
    if: github.event_name != 'push' || github.ref == 'refs/heads/main'
    
    strategy:
      matrix:
        chart:
          - name: runtime-api
            path: charts/runtime-api
          - name: image-loader
            path: charts/image-loader
          - name: openhands
            path: charts/openhands
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
          
      - name: Test ${{ matrix.chart.name }} chart with default values
        run: |
          echo "Testing ${{ matrix.chart.name }} chart with default values"
          echo "Updating dependencies for ${{ matrix.chart.name }}"
          helm dependency update ${{ matrix.chart.path }}
          
          echo "Running helm lint for ${{ matrix.chart.name }}"
          helm lint ${{ matrix.chart.path }}
          if [ $? -ne 0 ]; then
            echo "Helm lint test failed for ${{ matrix.chart.name }}"
            exit 1
          fi
          echo "Helm lint test passed for ${{ matrix.chart.name }}"
          
          echo "Running helm template for ${{ matrix.chart.name }}"
          helm template ${{ matrix.chart.path }} --debug
          if [ $? -ne 0 ]; then
            echo "Helm template test failed for ${{ matrix.chart.name }}"
            exit 1
          fi
          echo "Helm template test passed for ${{ matrix.chart.name }}"

  publish-charts:
    runs-on: ubuntu-latest
    needs: test-charts
    # Publish on pushes to main or manual triggers
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        chart:
          - name: runtime-api
            path: charts/runtime-api
            repository: openhands-cloud-runtime-api
          - name: image-loader
            path: charts/image-loader
            repository: openhands-cloud-image-loader
          - name: openhands
            path: charts/openhands
            repository: openhands-cloud
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Publish ${{ matrix.chart.name }} chart to GHCR
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: ${{ matrix.chart.name }}
          repository: ${{ matrix.chart.repository }}
          path: ${{ matrix.chart.path }}
          registry: ghcr.io/${{ github.repository_owner }}
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          update_dependencies: 'true'
          tag: auto