name: Helm Charts CI/CD

on:
  # Run tests on all branches and commits
  push:
  pull_request:
  # Only publish on main branch when charts are modified
  workflow_dispatch:

jobs:
  test-charts:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        chart:
          - name: runtime-api
            path: charts/runtime-api
          - name: image-loader
            path: charts/image-loader
          - name: openhands
            path: charts/openhands
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
          
      - name: Test Helm Chart with default values
        run: |
          echo "Testing ${{ matrix.chart.name }} chart with default values"
          echo "Updating dependencies for ${{ matrix.chart.name }}"
          helm dependency update ${{ matrix.chart.path }}
          echo "Running helm template for ${{ matrix.chart.name }}"
          helm template ${{ matrix.chart.path }} --debug
          if [ $? -ne 0 ]; then
            echo "Helm template test failed for ${{ matrix.chart.name }}"
            exit 1
          fi
          echo "Helm template test passed for ${{ matrix.chart.name }}"

  publish-charts:
    runs-on: ubuntu-latest
    needs: test-charts
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main' && contains(join(github.event.commits.*.modified, ' '), 'charts/')) || 
      github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        chart:
          - name: runtime-api
            path: charts/runtime-api
            repository: openhands-cloud-runtime-api
          - name: image-loader
            path: charts/image-loader
            repository: openhands-cloud-image-loader
          - name: openhands
            path: charts/openhands
            repository: openhands-cloud
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update Helm dependencies
        run: |
          echo "Updating dependencies for ${{ matrix.chart.name }}"
          helm dependency update ${{ matrix.chart.path }}

      - name: Publish Helm Chart
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: ${{ matrix.chart.name }}
          repository: ${{ matrix.chart.repository }}
          path: ${{ matrix.chart.path }}
          registry: ghcr.io/${{ github.repository_owner }}
          tag: auto